stages:
  - lint

Lint:
  stage: lint
  tags:
    - bfs
  script: 
    - cpplint.py --verbose=0 --filter=-whitespace,-line_length src/ams5812/ams5812.cc
    - cpplint.py --verbose=0 include/ams5915/ams5812.h
  